### ISSUE TITLE
Research changes needed to merge Southern Company into core integrations

### ISSUE THREAD

**Issue by dcsim0n** [Southern-Company-HA/southern-company-hacs#67]
The OPower integration was merged into core and we think there are changes that can be used to make southern company easier to merge.

**Comment by dcsim0n** [comment]
Attached is a diff from opower-hacs and opower core

[opowerdiff.txt](https://github.com/Southern-Company-HA/southern-company-hacs/files/13892142/opowerdiff.txt)

**Comment by dcsim0n** [comment]
A new quality scale system has been added to Core. Here is a list of items that will need attention for this integration.

```
  config-flow: done
  test-before-configure: done
  unique-config-entry: done
  config-flow-test-coverage:
    status: todo
    comment: need to create tests for the config flow
  runtime-data:
    status: todo
    comment: still uses hass.data
  test-before-setup: done
  appropriate-polling:
    status: todo
    comment: Add config options to allow user to set polling interval.
  entity-unique-id: done
  has-entity-name:
    status: todo
    comment: need to add _has_entity_name = True to SouthernCompanySensor
  entity-event-setup:
    status: exempt
    comment: No events to subscribe to
  dependency-transparency: done
  action-setup:
    status: exempt
    comment: No services to setup
  common-modules: done
  docs-high-level-description: todo
  docs-installation-instructions: todo
  docs-removal-instructions: todo
  docs-actions: todo
  brands: done
```
